Document: minesweeper
Title: Debian minesweeper Manual
Author: <insert document author here>
Abstract: This manual describes what minesweeper is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/minesweeper/minesweeper.sgml.gz

Format: postscript
Files: /usr/share/doc/minesweeper/minesweeper.ps.gz

Format: text
Files: /usr/share/doc/minesweeper/minesweeper.text.gz

Format: HTML
Index: /usr/share/doc/minesweeper/html/index.html
Files: /usr/share/doc/minesweeper/html/*.html
