.\" Manpage for MineSweeper.
.\" Contact adiwalv@gmail.com to correct errors or typos.
.TH "29 April 2019" "1.1" "MineSweeper man page"
.SH NAME
MineSweeper \- MineSweeper - The Classic
.SH SYNOPSIS
minesweeper
.SH DESCRIPTION
My take at the classic game. Well basically for the marks! 

In order to play, the player can simply enter the x,y coordinates of the block that they would like to select, separated by a comma. 
The numbers represent how many adjacent mines there are. The goal of the game is to find all the empty tiles without hitting any of the mines. The
number of mines is dependent upon the number of rows. So if there are 8 rows, then there are 8 mines in the field!

.SH BUGS
No known bugs.
.SH AUTHOR
Vikas Adiwal (adiwalv@gmail.com)
